const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Plugins.video,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.video.Cnds.IsPaused
	];
};
self.C3_JsPropNameTable = [
	{menu_course: 0},
	{menu_guideline: 0},
	{menu_test: 0},
	{menu_review: 0},
	{guideline: 0},
	{button_book: 0},
	{button_close: 0},
	{button_home: 0},
	{button_que: 0},
	{button_next: 0},
	{button_last: 0},
	{button_hear: 0},
	{button_sound: 0},
	{button_nextQ: 0},
	{train1: 0},
	{train2: 0},
	{train3: 0},
	{train4: 0},
	{train5: 0},
	{train6: 0},
	{train0: 0},
	{train_text: 0},
	{button_s1: 0},
	{button_s2: 0},
	{button_s3: 0},
	{button_s4: 0},
	{button_s5: 0},
	{button_s6: 0},
	{拖放: 0},
	{Ans1: 0},
	{Ans2: 0},
	{Ans3: 0},
	{Ans4: 0},
	{Ans5: 0},
	{Ans6: 0},
	{blank1: 0},
	{blank2: 0},
	{blank3: 0},
	{blank4: 0},
	{blank5: 0},
	{blank6: 0},
	{閃爍: 0},
	{choose1: 0},
	{choose2: 0},
	{choose3: 0},
	{choose4: 0},
	{choose5: 0},
	{choose6: 0},
	{button_letgo: 0},
	{button_test1: 0},
	{button_test2: 0},
	{button_test3: 0},
	{star: 0},
	{answer_blank: 0},
	{question_text: 0},
	{button_word_1: 0},
	{button_word_2: 0},
	{button_word_3: 0},
	{pause: 0},
	{視頻: 0},
	{background: 0},
	{Touch: 0},
	{knowledge: 0},
	{音頻: 0},
	{knowledge2: 0},
	{white: 0},
	{in病毒: 0},
	{in白血球: 0},
	{interaction_back: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{interaction化學物質: 0},
	{Sprite3: 0},
	{wordcard_1: 0},
	{wordcard_2: 0},
	{wordcard_3: 0},
	{backgroung_cut: 0},
	{interaction化學物質2: 0},
	{word_operation: 0},
	{Sprite4: 0},
	{chooses: 0},
	{Q1_obj: 0},
	{Ans: 0},
	{blanks: 0},
	{button_words: 0},
	{test1: 0},
	{test2: 0},
	{test3: 0},
	{Q2_num: 0},
	{sen_num: 0},
	{count_video: 0},
	{inter_count: 0}
];

self.InstanceType = {
	menu_course: class extends self.ISpriteInstance {},
	menu_guideline: class extends self.ISpriteInstance {},
	menu_test: class extends self.ISpriteInstance {},
	menu_review: class extends self.ISpriteInstance {},
	guideline: class extends self.ISpriteInstance {},
	button_book: class extends self.ISpriteInstance {},
	button_close: class extends self.ISpriteInstance {},
	button_home: class extends self.ISpriteInstance {},
	button_que: class extends self.ISpriteInstance {},
	button_next: class extends self.ISpriteInstance {},
	button_last: class extends self.ISpriteInstance {},
	button_hear: class extends self.ISpriteInstance {},
	button_sound: class extends self.ISpriteInstance {},
	button_nextQ: class extends self.ISpriteInstance {},
	train1: class extends self.ISpriteInstance {},
	train2: class extends self.ISpriteInstance {},
	train3: class extends self.ISpriteInstance {},
	train4: class extends self.ISpriteInstance {},
	train5: class extends self.ISpriteInstance {},
	train6: class extends self.ISpriteInstance {},
	train0: class extends self.ISpriteInstance {},
	train_text: class extends self.ISpriteInstance {},
	button_s1: class extends self.ISpriteInstance {},
	button_s2: class extends self.ISpriteInstance {},
	button_s3: class extends self.ISpriteInstance {},
	button_s4: class extends self.ISpriteInstance {},
	button_s5: class extends self.ISpriteInstance {},
	button_s6: class extends self.ISpriteInstance {},
	Ans1: class extends self.ISpriteInstance {},
	Ans2: class extends self.ISpriteInstance {},
	Ans3: class extends self.ISpriteInstance {},
	Ans4: class extends self.ISpriteInstance {},
	Ans5: class extends self.ISpriteInstance {},
	Ans6: class extends self.ISpriteInstance {},
	blank1: class extends self.ISpriteInstance {},
	blank2: class extends self.ISpriteInstance {},
	blank3: class extends self.ISpriteInstance {},
	blank4: class extends self.ISpriteInstance {},
	blank5: class extends self.ISpriteInstance {},
	blank6: class extends self.ISpriteInstance {},
	choose1: class extends self.ISpriteInstance {},
	choose2: class extends self.ISpriteInstance {},
	choose3: class extends self.ISpriteInstance {},
	choose4: class extends self.ISpriteInstance {},
	choose5: class extends self.ISpriteInstance {},
	choose6: class extends self.ISpriteInstance {},
	button_letgo: class extends self.ISpriteInstance {},
	button_test1: class extends self.ISpriteInstance {},
	button_test2: class extends self.ISpriteInstance {},
	button_test3: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	answer_blank: class extends self.ISpriteInstance {},
	question_text: class extends self.ISpriteInstance {},
	button_word_1: class extends self.ISpriteInstance {},
	button_word_2: class extends self.ISpriteInstance {},
	button_word_3: class extends self.ISpriteInstance {},
	視頻: class extends self.IWorldInstance {},
	background: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	knowledge: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	knowledge2: class extends self.ISpriteInstance {},
	white: class extends self.ISpriteInstance {},
	in病毒: class extends self.ISpriteInstance {},
	in白血球: class extends self.ISpriteInstance {},
	interaction_back: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	interaction化學物質: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	wordcard_1: class extends self.ISpriteInstance {},
	wordcard_2: class extends self.ISpriteInstance {},
	wordcard_3: class extends self.ISpriteInstance {},
	backgroung_cut: class extends self.ISpriteInstance {},
	interaction化學物質2: class extends self.ISpriteInstance {},
	word_operation: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	chooses: class extends self.ISpriteInstance {},
	Q1_obj: class extends self.ISpriteInstance {},
	Ans: class extends self.ISpriteInstance {},
	blanks: class extends self.ISpriteInstance {},
	button_words: class extends self.ISpriteInstance {}
}